theme: minima
title: "FGG Wars Правила"

header_pages:
  - rules/Победа.md
  - rules/Территория.md
  - rules/Текущая-игра.md
  - rules/Колесо.md
  - rules/Таймер.md
  - rules/Квесты.md
  - rules/Перки.md
  - rules/Предметы.md
  - rules/Характеристики.md
  - rules/Список-желаемого.md
