theme: minima

header_pages:
  - index.md
  - Квесты.md
  - Колесо.md
  - Перки.md
  - Победа.md
  - Предметы.md
  - Список_желаемого.md
  - Таймер.md
  - Текущая_игра.md
  - Территория.md
  - Характеристики.md
